name: CI-BlackDuck-SCA

on:
  push:
    branches: [ main, master, develop, stage, release, add-empty-file ]
  pull_request:
    branches: [ main, master, develop, stage, release, add-empty-file ]
  workflow_dispatch:

jobs:
  blackduck_scan:
    runs-on: [ubuntu-latest]

    permissions:
      contents: read
      pull-requests: write
      actions: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3


      - name: Black Duck SCA PR Scan
        id: black-duck-pr-scan
        if: ${{ github.event_name != 'pull_request' }}
        uses: blackduck-inc/black-duck-security-scan@v2.1.1

        ### Use below configuration to set specific detect environment variables
        env:
          DETECT_PROJECT_NAME: "GenAI"
          DETECT_PROJECT_VERSION_NAME: "test1"
          BLACKDUCK_TRUST_CERT: true
        with:
          blackducksca_url: ${{ vars.BLACKDUCK_SERVER_URL  }}
          blackducksca_token: ${{ secrets.BLACKDUCK_API_TOKEN }}
          blackducksca_scan_full: true

          ### Below configuration is used to enable automatic pull request comment based on Black Duck SCA scan result
          blackducksca_fixpr_enabled: true
          blackducksca_fixpr_filter_severities: CRITICAL
          github_token: ${{ secrets.GITHUB_TOKEN }}
          blackducksca_reports_sarif_create: true
          blackducksca_upload_sarif_report: true

          ### Arbitrary product-related CL arguments
          detect_search_depth: 10
          detect_args: '--detect.diagnostic=true --logging.level.detect=TRACE --detect.blackduck.signature.scanner.arguments="--min-scan-interval=0"'
